-- Update the 'investors' page in the site_pages table with the new english text
UPDATE site_pages
SET content_blocks = '[
  {"id": "1", "type": "heading", "content": "Why Invest in Sporthorses?", "size": "text-4xl"},
  {"id": "2", "type": "text", "content": "The equestrian sport has transitioned from a passion-driven pursuit into a highly professional, multi-billion-dollar global industry. At the pinnacle of this industry sits the showjumping market, where demand for top-tier equine athletes consistently outpaces supply.", "size": "text-lg"},
  {"id": "3", "type": "text", "content": "By partnering with Equiviesa, you gain direct access to our extensive network in the heart of the equestrian world: the Netherlands, Belgium, and Germany. We meticulously select, train, and export exceptional horses to the United States, where the market commands significant premiums.", "size": "text-lg"},
  {"id": "4", "type": "heading", "content": "The Future of Exclusive Capital", "size": "text-3xl"},
  {"id": "5", "type": "text", "content": "In an era dominated by volatile digital markets, algorithmic trading, and unpredictable stock prices, the modern investor seeks robust diversification. Within the portfolios of the world''s most successful investors, a clear trend is emerging: the shift towards tangible, rare, and performance-driven alternative assets. At the absolute intersection of passion, prestige, and exponential returns lies the top sport of showjumping. Investing in elite sporthorses today is no longer an opaque gamble, but a highly strategic and data-driven wealth management decision.", "size": "text-lg"},
  {"id": "6", "type": "heading", "content": "An Uncorrelated Asset Class", "size": "text-2xl"},
  {"id": "7", "type": "text", "content": "The biggest advantage of top sporthorses as an investment is that their value is completely uncorrelated to traditional financial markets. When stocks fall or inflation rises, the intrinsic value of a Grand Prix sporthorse remains exceptionally stable. International top sport is a multi-billion dollar industry driven by Ultra-High-Net-Worth Individuals (UHNWIs), royal families, and global syndicates. The demand for top sport horses capable of performing at the 1.60m level consistently outstrips supply. This creates a scarcity economy where prices for proven talents reach record highs year after year.", "size": "text-lg"},
  {"id": "8", "type": "heading", "content": "From Promise to Blue-Chip: Exponential Value Appreciation", "size": "text-2xl"},
  {"id": "9", "type": "text", "content": "The financial lifecycle of a sporthorse offers unique opportunities for incredible ROI (Return on Investment). The strategy is akin to venture capital: we identify young, raw talent with unprecedented potential. By pairing them with world-class riders and state-of-the-art training programs, we transform these promises into proven top athletes. A 5-year-old talent can, once it proves itself on international stages as a 9- or 10-year-old, multiply its value sixfold. In addition to their trading value, top athletes generate direct returns through explosively rising prize money on circuits like the Global Champions Tour, and through exclusive breeding rights (genetics and embryo trading) that create a lasting income stream.", "size": "text-lg"},
  {"id": "10", "type": "heading", "content": "Investment Rooted in Data and Science", "size": "text-2xl"},
  {"id": "11", "type": "text", "content": "Where horse trading used to revolve around ''gut feeling'', in 2026 it has become an exact science. Our selection procedure eliminates risks by utilizing advanced biometric analyses, predictive genetic models, and detailed veterinary AI scans. We invest exclusively in athletes whose data demonstrates they possess the perfect balance of physical power, reflexes, health, and the mental perseverance required for the absolute world top. You are not investing in an animal; you are investing in a carefully calibrated top sports machine.", "size": "text-lg"},
  {"id": "12", "type": "heading", "content": "Prestige, Network, and the Ultimate Lifestyle", "size": "text-2xl"},
  {"id": "13", "type": "text", "content": "Finally, owning an elite sporthorse offers a dividend that cannot be captured in any graph: exclusive access. As an investor, you buy into one of the most closed and prestigious ecosystems in the world. You gain VIP access to glamorous events from Monaco to Miami and from Paris to Doha. Ownership provides an unparalleled platform for high-level networking, where you stand shoulder-to-shoulder with influential leaders, CEOs, and other top investors in the VIP stands.", "size": "text-lg"},
  {"id": "14", "type": "heading", "content": "Return on Investment (ROI)", "size": "text-4xl"},
  {"id": "15", "type": "text", "content": "Investing in sporthorses is classified as an alternative asset class. While it carries inherent risks, the potential returns significantly outpace traditional markets when managed by experts. It is the perfect synergy between calculated financial return and an extraordinary lifestyle. It is capital that breathes, performs, and wins.", "size": "text-lg"}
]'::jsonb
WHERE slug = 'investors';

-- If it doesn't exist yet, insert it
INSERT INTO site_pages (slug, title, hero_image, content_blocks)
SELECT 'investors', 'Invest in Excellence', '/about-bg.jpg', '[
  {"id": "1", "type": "heading", "content": "Why Invest in Sporthorses?", "size": "text-4xl"},
  {"id": "2", "type": "text", "content": "The equestrian sport has transitioned from a passion-driven pursuit into a highly professional, multi-billion-dollar global industry. At the pinnacle of this industry sits the showjumping market, where demand for top-tier equine athletes consistently outpaces supply.", "size": "text-lg"},
  {"id": "3", "type": "text", "content": "By partnering with Equiviesa, you gain direct access to our extensive network in the heart of the equestrian world: the Netherlands, Belgium, and Germany. We meticulously select, train, and export exceptional horses to the United States, where the market commands significant premiums.", "size": "text-lg"},
  {"id": "4", "type": "heading", "content": "The Future of Exclusive Capital", "size": "text-3xl"},
  {"id": "5", "type": "text", "content": "In an era dominated by volatile digital markets, algorithmic trading, and unpredictable stock prices, the modern investor seeks robust diversification. Within the portfolios of the world''s most successful investors, a clear trend is emerging: the shift towards tangible, rare, and performance-driven alternative assets. At the absolute intersection of passion, prestige, and exponential returns lies the top sport of showjumping. Investing in elite sporthorses today is no longer an opaque gamble, but a highly strategic and data-driven wealth management decision.", "size": "text-lg"},
  {"id": "6", "type": "heading", "content": "An Uncorrelated Asset Class", "size": "text-2xl"},
  {"id": "7", "type": "text", "content": "The biggest advantage of top sporthorses as an investment is that their value is completely uncorrelated to traditional financial markets. When stocks fall or inflation rises, the intrinsic value of a Grand Prix sporthorse remains exceptionally stable. International top sport is a multi-billion dollar industry driven by Ultra-High-Net-Worth Individuals (UHNWIs), royal families, and global syndicates. The demand for top sport horses capable of performing at the 1.60m level consistently outstrips supply. This creates a scarcity economy where prices for proven talents reach record highs year after year.", "size": "text-lg"},
  {"id": "8", "type": "heading", "content": "From Promise to Blue-Chip: Exponential Value Appreciation", "size": "text-2xl"},
  {"id": "9", "type": "text", "content": "The financial lifecycle of a sporthorse offers unique opportunities for incredible ROI (Return on Investment). The strategy is akin to venture capital: we identify young, raw talent with unprecedented potential. By pairing them with world-class riders and state-of-the-art training programs, we transform these promises into proven top athletes. A 5-year-old talent can, once it proves itself on international stages as a 9- or 10-year-old, multiply its value sixfold. In addition to their trading value, top athletes generate direct returns through explosively rising prize money on circuits like the Global Champions Tour, and through exclusive breeding rights (genetics and embryo trading) that create a lasting income stream.", "size": "text-lg"},
  {"id": "10", "type": "heading", "content": "Investment Rooted in Data and Science", "size": "text-2xl"},
  {"id": "11", "type": "text", "content": "Where horse trading used to revolve around ''gut feeling'', in 2026 it has become an exact science. Our selection procedure eliminates risks by utilizing advanced biometric analyses, predictive genetic models, and detailed veterinary AI scans. We invest exclusively in athletes whose data demonstrates they possess the perfect balance of physical power, reflexes, health, and the mental perseverance required for the absolute world top. You are not investing in an animal; you are investing in a carefully calibrated top sports machine.", "size": "text-lg"},
  {"id": "12", "type": "heading", "content": "Prestige, Network, and the Ultimate Lifestyle", "size": "text-2xl"},
  {"id": "13", "type": "text", "content": "Finally, owning an elite sporthorse offers a dividend that cannot be captured in any graph: exclusive access. As an investor, you buy into one of the most closed and prestigious ecosystems in the world. You gain VIP access to glamorous events from Monaco to Miami and from Paris to Doha. Ownership provides an unparalleled platform for high-level networking, where you stand shoulder-to-shoulder with influential leaders, CEOs, and other top investors in the VIP stands.", "size": "text-lg"},
  {"id": "14", "type": "heading", "content": "Return on Investment (ROI)", "size": "text-4xl"},
  {"id": "15", "type": "text", "content": "Investing in sporthorses is classified as an alternative asset class. While it carries inherent risks, the potential returns significantly outpace traditional markets when managed by experts. It is the perfect synergy between calculated financial return and an extraordinary lifestyle. It is capital that breathes, performs, and wins.", "size": "text-lg"}
]'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM site_pages WHERE slug = 'investors'
);
